#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -r c3po_data*
rm -r c3po_tim*
rm -r c3po_sampling
rm -r c3po_binning

cd octave
rm *.eps

# ----------------------------------------------------------------- end-of-file
